# Generated by Django 5.2.3 on 2025-06-29 08:32

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='text',
            field=wagtail.fields.RichTextField(),
        ),
    ]
